apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-jenkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-jenkin
  template:
    metadata:
      labels:
        app: nginx-jenkin
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkin-service
spec:
  type: NodePort
  selector:
    app: nginx-jenkin
  ports:
  - protocol: TCP
    port: 80           # Port on which the service is exposed
    targetPort: 80     # Port on which the container is listening
    nodePort: 30088    # Port on the node to expose
